---

- name: Stop MySQL
  become: true
  systemd:
    name: mysqld
    state: stopped

- name: set environment variables
  become: true
  shell: systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"

- name: Start MySQL
  become: true
  systemd:
    name: mysqld
    state: started

- name: Clear root password
  command: mysql -u root --execute="UPDATE mysql.user SET authentication_string=null WHERE user='root';"

- name: Stop MySQL
  become: true
  systemd:
    name: mysqld
    state: stopped

- name: Unset environment variables
  become: true
  shell: systemctl unset-environment MYSQLD_OPTS

- name: Start MySQL
  become: true
  systemd:
    name: mysqld
    state: started

- name: Set root password
  command: mysql -u root --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';"
