---

- name: Configure php.ini
  become: true
  template:
    src: etc/php.ini.j2
    dest: /etc/php.ini
    force: "yes"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart httpd

- name: Stat 15-xdebug.ini
  stat:
    path: /etc/php.d/15-xdebug.ini
  register: xdebug

- name: Configure 15-xdebug.ini
  become: true
  template:
    src: php.d/15-xdebug.ini.j2
    dest: /etc/php.d/15-xdebug.ini
    force: "yes"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart httpd
  when: xdebug.stat.exists == True
