---

- name: Add repository Remi
  become: true
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install PHP
  become: true
  yum:
    name: "{{ php_install_packages }}"
    enablerepo: remi-php73
    state: present
  notify:
    - Restart httpd
  
