---

- name: Download installer
  become: true
  get_url:
    url:  https://getcomposer.org/installer
    dest: /tmp

- name: Install Composer
  become: true
  command: "php /tmp/installer --install-dir=\"{{ composer_install_dir }}\" --filename=\"{{ composer_filename }}\" --version=\"{{ composer_version }}\""
